#
# SFU CMPT 756
#
# k8s yaml to deploy:
#   1 Deployment - this governs the logic (container)
#   1 Service - this opens up the logic
#   1 Service Account - this enable access control
#
# Notable observations:
#
# 1. the Service's .spec.ports[0] need to matches the Deployment's
#    .spec.template.spec.containers[0].ports
# 2. Deployment's .spec.template.spec.containers.livenessProbe & readinessProbe
#    can be removed to clean up the logs
# 3. You must supply your AWS specifics in the secret resource
#
# TODO: You must run the template processor to fill in the template variables "ZZ-*"
#
apiVersion: v1
kind: Service
metadata:
  name: images
  labels:
    app: images
spec:
  ports:
    - port: 30001
      name: http
  selector:
    app: images
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-images
  labels:
    account: SVC_IMAGES
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: images
  labels:
    app: images
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: images
      version: v1
  template:
    metadata:
      name: database-pod
      labels:
        app: images
        version: v1
    spec:
      serviceAccountName: svc-images
      containers:
        - name: images
          image: ZZ-CR-ID/ZZ-REG-ID/images:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 30001
