# apiVersion: networking.istio.io/v1beta1
# kind: VirtualService
# metadata:
#   name: logger
# spec:
#   hosts:
#     - logger
#   # This is an internal service, so is not announced to the gateway.
#   # With no "gateways" field, the default applies: Make this service
#   # known internally to every other service.
#   http:
#     - match:
#         - uri:
#             prefix: /api/v1/logger
#       rewrite:
#         uri: /api/v1/logger
#       route:
#         - destination:
#             host: logger
#             port:
#               number: 30003

#
# SFU CMPT 756
#
# Istio yaml to deploy a VirtualService
#
# DestinationRule lists the subset destination Kubernetes Services
# that will receive traffic from the Istio VirtualService.
# VirtualService routes URLs to the destinations, splitting the traffic
# across destinations according to weights.
#
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: logger
spec:
  host: logger
  subsets:
    - name: v1
      labels:
        version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: logger
spec:
  hosts:
    # We do not know the hostname of traffic from this gateway, so
    # apply this VS to every request entering it.
    - "*"
  # As an externally-visible service, this only applies to the gateway
  gateways:
    - c756marketplace-gateway
  http:
    - match:
        - uri:
            prefix: /api/v1/logger
      rewrite:
        uri: /api/v1/logger
      route:
        - weight: 100
          destination:
            host: logger
            port:
              number: 30003
            subset: v1
