apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: transaction
  labels:
    app: transaction
    release: c756
spec:
  namespaceSelector:
    matchNames:
      - c756marketplacens
  selector:
    matchLabels:
      app: transaction
  endpoints:
    - port: http
      path: /metrics
