# SFU CMPT 756
#
# Kubernetes yaml to deploy pods as Endpoints of a Service.
# The matchLabels connect this Deployment to a Service.
# There can be several Deployments implementing Endpoints of the same Service.
# Each Deployment will typically be a different version.
#
# The Istio VirtualService and DestinationRules will route traffic to the
# different Deployments.
#
# Deployment's .spec.template.spec.containers.livenessProbe & readinessProbe
#    can be removed to clean up the logs
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
      version: v1
  template:
    metadata:
      name: users-pod
      labels:
        app: users
        version: v1
    spec:
      serviceAccountName: svc-users
      containers:
        - name: users
          image: "ghcr.io/krp30/users:v1"
          imagePullPolicy: Always
          ports:
            - containerPort: 30000
          livenessProbe:
            httpGet:
              path: /api/v1/users/health
              port: 30000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/v1/users/readiness
              port: 30000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 5
