apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: users
  labels:
    app: users
    release: c756
spec:
  namespaceSelector:
    matchNames:
      - c756marketplacens
  selector:
    matchLabels:
      app: users
  endpoints:
    - port: http
      path: /metrics
